/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedCustomerRouteImport } from './routes/_authed/customer'
import { Route as AuthedDevFormpanelTestRouteImport } from './routes/_authed/dev-formpanel-test'
import { Route as AuthedDriversRouteImport } from './routes/_authed/drivers'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed/notifications'
import { Route as AuthedPaymentsRouteImport } from './routes/_authed/payments'
import { Route as AuthedPayoutsRouteImport } from './routes/_authed/payouts'
import { Route as AuthedPricingRouteImport } from './routes/_authed/pricing'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedTripsRouteImport } from './routes/_authed/trips'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedVehiclesRouteImport } from './routes/_authed/vehicles'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomerRoute = AuthedCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDevFormpanelTestRoute = AuthedDevFormpanelTestRouteImport.update({
  id: '/dev-formpanel-test',
  path: '/dev-formpanel-test',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDriversRoute = AuthedDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPaymentsRoute = AuthedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPayoutsRoute = AuthedPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPricingRoute = AuthedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTripsRoute = AuthedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedVehiclesRoute = AuthedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/customer': typeof AuthedCustomerRoute
  '/dev-formpanel-test': typeof AuthedDevFormpanelTestRoute
  '/drivers': typeof AuthedDriversRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/payments': typeof AuthedPaymentsRoute
  '/payouts': typeof AuthedPayoutsRoute
  '/pricing': typeof AuthedPricingRoute
  '/settings': typeof AuthedSettingsRoute
  '/trips': typeof AuthedTripsRoute
  '/users': typeof AuthedUsersRoute
  '/vehicles': typeof AuthedVehiclesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/customer': typeof AuthedCustomerRoute
  '/dev-formpanel-test': typeof AuthedDevFormpanelTestRoute
  '/drivers': typeof AuthedDriversRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/payments': typeof AuthedPaymentsRoute
  '/payouts': typeof AuthedPayoutsRoute
  '/pricing': typeof AuthedPricingRoute
  '/settings': typeof AuthedSettingsRoute
  '/trips': typeof AuthedTripsRoute
  '/users': typeof AuthedUsersRoute
  '/vehicles': typeof AuthedVehiclesRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/customer': typeof AuthedCustomerRoute
  '/_authed/dev-formpanel-test': typeof AuthedDevFormpanelTestRoute
  '/_authed/drivers': typeof AuthedDriversRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/payments': typeof AuthedPaymentsRoute
  '/_authed/payouts': typeof AuthedPayoutsRoute
  '/_authed/pricing': typeof AuthedPricingRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/trips': typeof AuthedTripsRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/vehicles': typeof AuthedVehiclesRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/customer'
    | '/dev-formpanel-test'
    | '/drivers'
    | '/notifications'
    | '/payments'
    | '/payouts'
    | '/pricing'
    | '/settings'
    | '/trips'
    | '/users'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/customer'
    | '/dev-formpanel-test'
    | '/drivers'
    | '/notifications'
    | '/payments'
    | '/payouts'
    | '/pricing'
    | '/settings'
    | '/trips'
    | '/users'
    | '/vehicles'
    | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/customer'
    | '/_authed/dev-formpanel-test'
    | '/_authed/drivers'
    | '/_authed/notifications'
    | '/_authed/payments'
    | '/_authed/payouts'
    | '/_authed/pricing'
    | '/_authed/settings'
    | '/_authed/trips'
    | '/_authed/users'
    | '/_authed/vehicles'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customer': {
      id: '/_authed/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof AuthedCustomerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dev-formpanel-test': {
      id: '/_authed/dev-formpanel-test'
      path: '/dev-formpanel-test'
      fullPath: '/dev-formpanel-test'
      preLoaderRoute: typeof AuthedDevFormpanelTestRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/drivers': {
      id: '/_authed/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthedDriversRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/payments': {
      id: '/_authed/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthedPaymentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/payouts': {
      id: '/_authed/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AuthedPayoutsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pricing': {
      id: '/_authed/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthedPricingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trips': {
      id: '/_authed/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthedTripsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/vehicles': {
      id: '/_authed/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthedVehiclesRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCustomerRoute: typeof AuthedCustomerRoute
  AuthedDevFormpanelTestRoute: typeof AuthedDevFormpanelTestRoute
  AuthedDriversRoute: typeof AuthedDriversRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedPaymentsRoute: typeof AuthedPaymentsRoute
  AuthedPayoutsRoute: typeof AuthedPayoutsRoute
  AuthedPricingRoute: typeof AuthedPricingRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTripsRoute: typeof AuthedTripsRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedVehiclesRoute: typeof AuthedVehiclesRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCustomerRoute: AuthedCustomerRoute,
  AuthedDevFormpanelTestRoute: AuthedDevFormpanelTestRoute,
  AuthedDriversRoute: AuthedDriversRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedPaymentsRoute: AuthedPaymentsRoute,
  AuthedPayoutsRoute: AuthedPayoutsRoute,
  AuthedPricingRoute: AuthedPricingRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTripsRoute: AuthedTripsRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedVehiclesRoute: AuthedVehiclesRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
